"""add teams, team_aliases, matches

Revision ID: 2489841d4332
Revises: 
Create Date: 2026-09-23 16:42:34.494345
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2489841d4332'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=7), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.SmallInteger(), nullable=True),
    sa.Column('away_goals', sa.SmallInteger(), nullable=True),
    sa.Column('home_shots', sa.SmallInteger(), nullable=True),
    sa.Column('away_shots', sa.SmallInteger(), nullable=True),
    sa.Column('home_shots_on_target', sa.SmallInteger(), nullable=True),
    sa.Column('away_shots_on_target', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('home_goals >= 0 AND away_goals >= 0', name=op.f('ck_matches_non_negative_goals')),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_matches_distinct_teams')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('season', 'home_team_id', 'away_team_id', name=op.f('uq_matches_season_home_team_id_away_team_id'))
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_aliases_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_aliases')),
    sa.UniqueConstraint('alias', name=op.f('uq_team_aliases_alias'))
    )
    op.create_index(op.f('ix_team_aliases_team_id'), 'team_aliases', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_aliases_team_id'), table_name='team_aliases')
    op.drop_table('team_aliases')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
